version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-cart
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: shopping-cart-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping-cart-db
    ports:
      - '5433:5432'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data